development:
  adapter: postgresql
  encoding: unicode
  database: silvia_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: silvia_test
  pool: 5
  min_messages: warning
  host: localhost
